In [1]:
# Installs Unsloth, Xformers (Flash Attention) and all other packages!
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps "xformers<0.0.26" trl peft accelerate bitsandbytes

Collecting unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-68qry1_k/unsloth_3b0d404c538d4c7699b2124c84c60d10
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-68qry1_k/unsloth_3b0d404c538d4c7699b2124c84c60d10
  Resolved https://github.com/unslothai/unsloth.git to commit 4211cc01409e3ced4f7abebaf68e244193b46e2c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tyro (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-0.8.3-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.0/102.0 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: transformers>=4.38.2 in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.40.1)
Collecting datasets>=2.16.0 (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-2.19.1-py3-none-any.whl (542 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 12.3 MB/s eta 0:00:00
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.99)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.66.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.43.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.25.2)
Requirement already satisfied: protobuf<4.0.0 in /usr/local/lib/python3.10/dist-packages (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.20.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.14.0)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.5 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.31.0)
Collecting xxhash (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 14.7 MB/s eta 0:00:00
Collecting multiprocess (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 17.5 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2024.3.1,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.9.5)
Collecting huggingface-hub>=0.21.2 (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading huggingface_hub-0.23.0-py3-none-any.whl (401 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 15.6 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.38.2->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2023.12.25)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.38.2->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.38.2->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.3)
Requirement already satisfied: docstring-parser>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.16)
Requirement already satisfied: typing-extensions>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.11.0)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (13.7.1)
Collecting shtab>=1.5.6 (from tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading shtab-1.7.1-py3-none-any.whl (14 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2024.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.16.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2024.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1.0->tyro->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.16.0->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.16.0)
Building wheels for collected packages: unsloth
  Building wheel for unsloth (pyproject.toml) ... done
  Created wheel for unsloth: filename=unsloth-2024.4-py3-none-any.whl size=101150 sha256=16098d45e37530308a64c0634398f3d084fb296c6ccd04c4cd026d3a0a360647
  Stored in directory: /tmp/pip-ephem-wheel-cache-hm3lsyjd/wheels/ed/d4/e9/76fb290ee3df0a5fc21ce5c2c788e29e9607a2353d8342fd0d
Successfully built unsloth
Installing collected packages: xxhash, unsloth, shtab, dill, multiprocess, huggingface-hub, tyro, datasets
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
Successfully installed datasets-2.19.1 dill-0.3.8 huggingface-hub-0.23.0 multiprocess-0.70.16 shtab-1.7.1 tyro-0.8.3 unsloth-2024.4 xxhash-3.4.1
Collecting xformers<0.0.26
  Downloading xformers-0.0.25.post1-cp310-cp310-manylinux2014_x86_64.whl (222.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.5/222.5 MB 5.0 MB/s eta 0:00:00
Collecting trl
  Downloading trl-0.8.6-py3-none-any.whl (245 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.2/245.2 kB 28.5 MB/s eta 0:00:00
Collecting peft
  Downloading peft-0.10.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 23.4 MB/s eta 0:00:00
Collecting accelerate
  Downloading accelerate-0.30.0-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 38.1 MB/s eta 0:00:00
Collecting bitsandbytes
  Downloading bitsandbytes-0.43.1-py3-none-manylinux_2_24_x86_64.whl (119.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 8.4 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, xformers, trl, peft, accelerate
Successfully installed accelerate-0.30.0 bitsandbytes-0.43.1 peft-0.10.0 trl-0.8.6 xformers-0.0.25.post1

In [2]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/mistral-7b-bnb-4bit",
    "unsloth/mistral-7b-instruct-v0.2-bnb-4bit",
    "unsloth/llama-2-7b-bnb-4bit",
    "unsloth/gemma-7b-bnb-4bit",
    "unsloth/gemma-7b-it-bnb-4bit", # Instruct version of Gemma 7b
    "unsloth/gemma-2b-bnb-4bit",
    "unsloth/gemma-2b-it-bnb-4bit", # Instruct version of Gemma 2b
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/gemma-2b-bnb-4bit", # Choose ANY! eg teknium/OpenHermes-2.5-Mistral-7B
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

==((====))==  Unsloth: Fast Gemma patching release 2024.4
   \\   /|    GPU: Tesla T4. Max memory: 14.748 GB. Platform = Linux.
O^O/ \_/ \    Pytorch: 2.2.1+cu121. CUDA = 7.5. CUDA Toolkit = 12.1.
\        /    Bfloat16 = FALSE. Xformers = 0.0.25.post1. FA = False.
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth

Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.

model.safetensors:   0%|          | 0.00/2.07G [00:00<?, ?B/s]

Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

In [3]:
# how to read json file with pandas
import pandas as pd
df = pd.read_json('/content/CSE4078S24_Dataset2.json')
df

,instruction,input,output
0,Aşağıdaki ifadeye karşılık ver.,Ne tür telefon(lar)ınız var?,Bende bir pixel var. Oldukça iyi. Daha önce sa...
1,Aşağıdaki ifadeye karşılık ver.,Bende bir pixel var. Oldukça iyi. Daha önce sa...,Gerçekten 15 dakikada tamamen şarj oluyor mu?
2,Aşağıdaki ifadeye karşılık ver.,Gerçekten 15 dakikada tamamen şarj oluyor mu?,Oldukça hızlı. Hiç zaman tutmadım ama yarım sa...
3,Aşağıdaki ifadeye karşılık ver.,Ne tür telefon(lar)ınız var?,Samsung Galaxy J1. Bu benim ilk cep telefonum ...
4,Aşağıdaki ifadeye karşılık ver.,Samsung Galaxy J1. Bu benim ilk cep telefonum ...,Ne düşünüyorsun? Beğenmediğin bir şey var mı?
...,...,...,...
5952,Aşağıdaki ifadeye karşılık ver.,Haftalık planlarınız neler?,Salı günü biriyle takılacağım ama şu ana kadar...
5953,Aşağıdaki ifadeye karşılık ver.,Salı günü biriyle takılacağım ama şu ana kadar...,Güzel ve dinlendirici bir haftaya benziyor! Sa...
5954,Aşağıdaki ifadeye karşılık ver.,Balodan nefret eden başka biri var mı?,Balodan nefret etmedim.\r\n\r\nAncak evlenme t...
5955,Aşağıdaki ifadeye karşılık ver.,Balodan nefret etmedim.\r\n\r\nAncak evlenme t...,İnanılmaz derecede geyler.
5956,Aşağıdaki ifadeye karşılık ver.,Balodan nefret etmedim.\r\n\r\nAncak evlenme t...,İnanılmaz derecede geyler.

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [4]:
alpaca = {
    'instruction': "",
    'input': "",
    'output':""
}

In [5]:
# open a new dataframe
df_new = pd.DataFrame()

In [6]:
def get_token_length(text):

  # Tokenize the text
  tokens = tokenizer.tokenize(text)

  # Get the token length
  token_length = len(tokens)

  return token_length

In [7]:
# read df row by row and concat it to another df

for index, row in df.iterrows():
  if get_token_length(alpaca['instruction']) > 512:
    alpaca = {
    'instruction': "",
    'input': "",
    'output':""
    }
    print(f'At index {index}')

  if index == 0 or alpaca['instruction'] == "":
    alpaca['instruction'] = alpaca['instruction'] + 'Kullanıcı : '  + row['input'] + '\n'
    alpaca['output'] = row['output']
  else:
    # check if index is divisble by two
    if index % 2 == 1:
      alpaca['instruction'] = alpaca['instruction'] + 'Ajan : '  + row['input'] + '\n'
      alpaca['output'] = row['output']
    else:
      alpaca['instruction'] = alpaca['instruction'] + 'Kullanıcı : '  + row['input'] + '\n'
      alpaca['output'] = row['output']
  # concat this alpaca to a dataframe
  df_new = pd.concat([df_new, pd.DataFrame([alpaca])])

At index 30
At index 58
At index 79
At index 111
At index 140
At index 164
At index 195
At index 224
At index 251
At index 277
At index 309
At index 338
At index 356
At index 384
At index 409
At index 427
At index 459
At index 485
At index 512
At index 537
At index 565
At index 591
At index 618
At index 646
At index 669
At index 694
At index 721
At index 748
At index 766
At index 795
At index 822
At index 848
At index 887
At index 916
At index 946
At index 973
At index 1007
At index 1033
At index 1065
At index 1094
At index 1115
At index 1143
At index 1196
At index 1237
At index 1265
At index 1291
At index 1319
At index 1347
At index 1374
At index 1406
At index 1432
At index 1457
At index 1491
At index 1509
At index 1533
At index 1568
At index 1599
At index 1626
At index 1657
At index 1684
At index 1715
At index 1744
At index 1796
At index 1868
At index 1928
At index 1953
At index 1984
At index 2021
At index 2046
At index 2069
At index 2097
At index 2126
At index 2153
At index 2181
At index 2213
At index 2241
At index 2270
At index 2300
At index 2327
At index 2357
At index 2383
At index 2410
At index 2437
At index 2464
At index 2493
At index 2520
At index 2551
At index 2579
At index 2612
At index 2641
At index 2685
At index 2754
At index 2815
At index 2851
At index 2888
At index 2912
At index 2940
At index 2966
At index 2993
At index 3020
At index 3046
At index 3081
At index 3105
At index 3130
At index 3158
At index 3182
At index 3205
At index 3231
At index 3258
At index 3289
At index 3328
At index 3367
At index 3413
At index 3448
At index 3482
At index 3515
At index 3550
At index 3581
At index 3612
At index 3637
At index 3661
At index 3691
At index 3720
At index 3753
At index 3781
At index 3810
At index 3837
At index 3859
At index 3893
At index 3921
At index 3945
At index 3978
At index 4005
At index 4041
At index 4068
At index 4093
At index 4114
At index 4135
At index 4157
At index 4188
At index 4217
At index 4242
At index 4260
At index 4282
At index 4297
At index 4333
At index 4353
At index 4379
At index 4408
At index 4435
At index 4460
At index 4485
At index 4511
At index 4537
At index 4563
At index 4595
At index 4625
At index 4659
At index 4685
At index 4720
At index 4758
At index 4787
At index 4820
At index 4841
At index 4863
At index 4880
At index 4900
At index 4928
At index 4954
At index 4981
At index 5011
At index 5042
At index 5072
At index 5098
At index 5128
At index 5159
At index 5192
At index 5223
At index 5251
At index 5281
At index 5311
At index 5342
At index 5365
At index 5391
At index 5418
At index 5448
At index 5471
At index 5497
At index 5527
At index 5552
At index 5587
At index 5608
At index 5637
At index 5658
At index 5678
At index 5709
At index 5740
At index 5769
At index 5797
At index 5830
At index 5855
At index 5883
At index 5907
At index 5938

In [8]:
df_new

,instruction,input,output
0,Kullanıcı : Ne tür telefon(lar)ınız var?\n,,Bende bir pixel var. Oldukça iyi. Daha önce sa...
0,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Gerçekten 15 dakikada tamamen şarj oluyor mu?
0,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Oldukça hızlı. Hiç zaman tutmadım ama yarım sa...
0,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Samsung Galaxy J1. Bu benim ilk cep telefonum ...
0,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Ne düşünüyorsun? Beğenmediğin bir şey var mı?
...,...,...,...
0,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Salı günü biriyle takılacağım ama şu ana kadar...
0,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Güzel ve dinlendirici bir haftaya benziyor! Sa...
0,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Balodan nefret etmedim.\r\n\r\nAncak evlenme t...
0,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,İnanılmaz derecede geyler.
0,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,İnanılmaz derecede geyler.

In [9]:
# add a sentence to instruction column of each row of df_new
df_new['instruction'] = df_new['instruction'] + '\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. '

In [10]:
# reset dataframe index
df_new = df_new.reset_index(drop=True)
df_new

,instruction,input,output
0,Kullanıcı : Ne tür telefon(lar)ınız var?\n\n Y...,,Bende bir pixel var. Oldukça iyi. Daha önce sa...
1,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Gerçekten 15 dakikada tamamen şarj oluyor mu?
2,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Oldukça hızlı. Hiç zaman tutmadım ama yarım sa...
3,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Samsung Galaxy J1. Bu benim ilk cep telefonum ...
4,Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan...,,Ne düşünüyorsun? Beğenmediğin bir şey var mı?
...,...,...,...
5952,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Salı günü biriyle takılacağım ama şu ana kadar...
5953,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Güzel ve dinlendirici bir haftaya benziyor! Sa...
5954,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,Balodan nefret etmedim.\r\n\r\nAncak evlenme t...
5955,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,İnanılmaz derecede geyler.
5956,Kullanıcı : Sonunda sevdiğim ilk alkolü buldum...,,İnanılmaz derecede geyler.

In [11]:
# read df_new row by row
json_list = []
for index, row in df_new.iterrows():
  json_list.append(
{
    'instruction': row['instruction'],
    'input': row['input'],
    'output':row['output']
})
json_list

[{'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Gerçekten 15 dakikada tamamen şarj oluyor mu?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Oldukça hızlı. Hiç zaman tutmadım ama yarım saatin altında.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Ne düşünüyorsun? Beğenmediğin bir şey var mı?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Bayıldım. Hoşuma gitmeyen hiçbir şey düşünemiyorum.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'LG Optimus V. Biliyorum, eski.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'İşini yapıyorsa, yeterince iyidir!'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Kendini öldürme OP.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Onlara bu zevki tattırmayacağım ;)'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Siktir et o ezikleri, senin arkadaşın olacağım/olacağız'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Teşekkürler :)'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Hayır, yapmadın!'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Ha?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Heh.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Ha?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Kesinlikle öyleyim! Hala kendimi bunun gerçekten olup olmadığını sorgularken buluyorum...'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Bu çok güzel!! Temelde benim gay hedeflerim.'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Bu çok güzel!! Temelde benim gay hedeflerim.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Eşcinsel kıç golleri. Burada çift anlamlı'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Bu çok güzel!! Temelde benim gay hedeflerim.\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Peki dostum, önemli kısmı atladın, içine soktun mu/sıkıştın mı?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Bu çok güzel!! Temelde benim gay hedeflerim.\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Peki dostum, önemli kısmı atladın, içine soktun mu/sıkıştın mı?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Ben bir kızım. Ayrıca. Tek motivasyonun bu mu?'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Bu çok güzel!! Temelde benim gay hedeflerim.\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Peki dostum, önemli kısmı atladın, içine soktun mu/sıkıştın mı?\nKullanıcı : Ben bir kızım. Ayrıca. Tek motivasyonun bu mu?\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'Tek motivasyonum bu değil, ama iyi bir patlama yaşamadıysanız hayat yaşamaya değmez'},
 {'instruction': 'Kullanıcı : Ne tür telefon(lar)ınız var?\nAjan : Bende bir pixel var. Oldukça iyi. Daha önce sahip olduğumdan çok daha iyi.\nKullanıcı : Gerçekten 15 dakikada tamamen şarj oluyor mu?\nAjan : Ne tür telefon(lar)ınız var?\nKullanıcı : Samsung Galaxy J1. Bu benim ilk cep telefonum ve 7 aydır kullanıyorum.\nAjan : Ne düşünüyorsun? Beğenmediğin bir şey var mı?\nKullanıcı : Ne tür telefon(lar)ınız var?\nAjan : LG Optimus V. Biliyorum, eski.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Kendini öldürme OP.\nKullanıcı : Arkadaşım kendimi öldürmemi söyledi :/\nAjan : Siktir et o ezikleri, senin arkadaşın olacağım/olacağız\nKullanıcı : Münazarada eyalet şampiyonluğu kazandım.\nAjan : Hayır, yapmadın!\nKullanıcı : Ha?\nAjan : Hayır, yapmadın!\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : TEBRİKLER! Umarım olabildiğince mutlu olursunuz :)\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Bu çok güzel!! Temelde benim gay hedeflerim.\nKullanıcı : Geçen gün bir kız arkadaşım mı oldu?\nAjan : Peki dostum, önemli kısmı atladın, içine soktun mu/sıkıştın mı?\nKullanıcı : Ben bir kızım. Ayrıca. Tek motivasyonun bu mu?\nAjan : Bir saat içinde evleniyorum.\n\n Yukarıdaki konuşma geçmişine göre sohbeti devam ettir. ',
  'input': '',
  'output': 'İyi şanslar. Neden ihtiyacın olduğunu bilmiyorum ama yine de iyi şanslar.'},

In [12]:
# save a list that contains json to file
import json
with open('json_list.json', 'w', encoding='utf-8') as file:
    json.dump(json_list, file, ensure_ascii=False)